# Module manifest for module 'psSearchGitHub'
# Generated by: skatterbrainz
# Generated on: 1/2/2026
# Last updated on: 1/2/2026
@{
	RootModule        = 'psSearchGitHub.psm1'
	ModuleVersion     = '1.0.0'
	# CompatiblePSEditions = @()
	GUID              = '4d58f922-35da-4675-94b0-100d84964ed7'
	Author            = 'skatterbrainz'
	CompanyName       = 'skatterbrainz'
	Copyright         = '(c) 2026 skatterbrainz. All rights reserved.'
	Description       = 'PowerShell tools for searching GitHub repositories and gists.'
	PowerShellVersion = '5.1'
	# PowerShellHostName = ''
	# PowerShellHostVersion = ''
	# DotNetFrameworkVersion = ''
	# ClrVersion = ''
	# ProcessorArchitecture = ''
	# RequiredModules = @()
	# RequiredAssemblies = @()
	# ScriptsToProcess = @()
	# TypesToProcess = @()
	# FormatsToProcess = @()
	# NestedModules = @()
	FunctionsToExport = @('Invoke-*', 'Get-*', 'Set-*', 'Remove-*', 'New-*', 'Search-*', 'Add-*', 'Update-*')
	CmdletsToExport   = @()
	VariablesToExport = '*'
	AliasesToExport   = @()
	# DscResourcesToExport = @()
	# ModuleList = @()
	# FileList = @()
	PrivateData       = @{
		PSData = @{
			Tags       = @('GitHub', 'Search', 'PowerShell', 'psSearchGitHub', 'skatterbrainz')
			LicenseUri = 'https://github.com/Skatterbrainz/psSearchGitHub/blob/main/LICENSE'
			ProjectUri = 'https://github.com/Skatterbrainz/psSearchGitHub'
			# IconUri = ''
			# ReleaseNotes = ''
			# Prerelease = ''
			# RequireLicenseAcceptance = $false
			# ExternalModuleDependencies = @()
		} # End of PSData hashtable
	} # End of PrivateData hashtable
	# HelpInfoURI = ''
	# DefaultCommandPrefix = ''
}